---
- name: Configure development environment
  hosts: all
  gather_facts: true
  become: true
  vars:
    target_user: "{{ ansible_user_id }}"
    user_home: "{{ ansible_env.HOME if ansible_connection == 'local' else '/home/' + target_user if ansible_os_family == 'Debian' else '/Users/' + target_user }}"
    oh_my_zsh_path: "{{ user_home }}/.oh-my-zsh"
    oh_my_zsh_custom_plugins_path: "{{ oh_my_zsh_path }}/custom/plugins"
    zsh_autosuggestions_repo: https://github.com/zsh-users/zsh-autosuggestions
    zsh_syntax_highlighting_repo: https://github.com/zsh-users/zsh-syntax-highlighting
    zsh_plugins_list:
      - sudo
      - z
      - history
      - git
      - extract
      - fzf
      - tmux
      - uv
      - bun
      - volta
      - docker
      - docker-compose
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    miniforge_install_path: "{{ user_home }}/miniforge3"
    use_volta: true

  roles:
    - common
    - zsh
    - python
    - nodejs
    - docker
    - tools
