---
# Ansible Galaxy requirements file
collections:
  - name: community.general
    version: 5.8.0

roles:
  - src: geerlingguy.homebrew
    version: 3.1.0
    name: homebrew
  - src: geerlingguy.pip
    version: 2.0.0
    name: pip
