---
- name: Install Zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Include Oh My Zsh installation tasks
  ansible.builtin.include_tasks: oh_my_zsh.yml

- name: Include Starship installation tasks
  ansible.builtin.include_tasks: starship.yml

- name: Get zsh path dynamically
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false
  become: false

- name: Change user's default shell to Zsh
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: "{{ zsh_path.stdout }}"
  become: true
  # Note: Changing shell might require logout/login to take effect.
  # For local execution, this might not immediately reflect in the current terminal.
