---
- name: Check if Oh My Zsh is already installed
  ansible.builtin.stat:
    path: "{{ oh_my_zsh_path }}"
  register: oh_my_zsh_check
  become: false # Check runs as user

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: >
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    creates: "{{ oh_my_zsh_path }}/oh-my-zsh.sh" # Idempotency check
  environment: # Pass environment variables to the script
    ZSH: "{{ oh_my_zsh_path }}"
    RUNZSH: "no" # Don't start zsh after install
    CHSH: "no"   # Don't change shell automatically, Ansible will do it
  become: false # Run as target_user
  when: not oh_my_zsh_check.stat.exists

- name: Clone zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: "{{ zsh_autosuggestions_repo }}"
    dest: "{{ oh_my_zsh_custom_plugins_path }}/zsh-autosuggestions"
    version: master # Or a specific tag/commit
  become: false

- name: Clone zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: "{{ zsh_syntax_highlighting_repo }}"
    dest: "{{ oh_my_zsh_custom_plugins_path }}/zsh-syntax-highlighting"
    version: master
  become: false

- name: Configure .zshrc with plugins
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ user_home }}/.zshrc"
    owner: "{{ target_user }}"
    group: "{{ target_user if ansible_os_family == 'Darwin' else target_user }}" # Group might be different on Linux
    mode: '0644'
  become: false # .zshrc is user-specific
