---
- name: Install dependencies for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: true

- name: Create Docker keyring directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: true

# 使用阿里云镜像源添加Docker的GPG密钥
- name: Add Docker's official GPG key from Aliyun
  ansible.builtin.shell:
    cmd: curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Add Docker's official GPG key from Aliyun (Debian)
  ansible.builtin.shell:
    cmd: curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  become: true
  when: ansible_distribution == "Debian"

# 使用阿里云镜像源设置Docker仓库
- name: Set up the Docker repository from Aliyun (Ubuntu)
  ansible.builtin.shell:
    cmd: >
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    creates: /etc/apt/sources.list.d/docker.list
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Set up the Docker repository from Aliyun (Debian)
  ansible.builtin.shell:
    cmd: >
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    creates: /etc/apt/sources.list.d/docker.list
  become: true
  when: ansible_distribution == "Debian"

# 安装Docker Engine、CLI和containerd
- name: Install Docker Engine and related packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: true

# 配置镜像加速器
- name: Create Docker daemon directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'
  become: true

- name: Configure Docker to use registry mirrors
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "registry-mirrors": [
          "https://registry.docker-cn.com",
          "https://hub-mirror.c.163.com",
          "https://mirror.baidubce.com",
          "https://docker.mirrors.ustc.edu.cn"
        ]
      }
    mode: '0644'
  become: true
  register: docker_daemon_config

- name: Restart Docker service if config changed
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  become: true
  when: docker_daemon_config.changed

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ target_user }}"
    groups: docker
    append: true
  become: true

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: true 
